# Generated by Django 6.0.3 on 2026-03-17 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='category',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='description',
        ),
        migrations.AlterField(
            model_name='watch',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.watch')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
