# Generated by Django 6.0.3 on 2026-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_percent', models.IntegerField(verbose_name='Phần trăm giảm (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
            ],
        ),
    ]
