# Generated by Django 6.0.3 on 2026-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='brand',
            field=models.CharField(default='Khác', max_length=100, verbose_name='Hãng sản xuất'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Chờ xác nhận CK', 'Chờ xác nhận CK'), ('Đã thanh toán (Thẻ)', 'Đã thanh toán (Thẻ)'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang giao hàng', 'Đang giao hàng'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang xử lý', max_length=50),
        ),
    ]
